local Constants = {}

Constants.SHIP_THRUST_POWER = 300
Constants.SHIP_ROTATION_SPEED = 180

Constants.PROJECTILE_SPEED = 1000

Constants.ASTEROID_MINIMUM_RADIUS = 40
Constants.ASTEROID_MAXIMUM_RADIUS = 55
Constants.ASTEROID_VERTEX_COUNT = 12
Constants.ASTEROID_MINIMUM_SPEED = 5
Constants.ASTEROID_MAXIMUM_SPEED = 50
Constants.ASTEROID_MINIMUM_RADIUS = 15


return Constants